### ISSUE TITLE
Error creating user at Step 3 of Install

### ISSUE THREAD

**Issue by Hz133Hz** [qexyorg/webmcr3#2]
File Application/WebMCR/User/Logic/DefaultLogic.php
```
$insert = Database::insert()
			->into('users')
			->columns(['group_id', 'email', 'password', 'login', 'gender',
				'firstname', 'lastname', 'avatar', 'birthday',
				'date_create', 'date_update', 'ip_create', 'ip_update'])
			->values([$group_id, $email, $password_hash, $login, $gender,
				$firstname, $lastname, $avatar, $birthday,
				$date_create, $date_update, $ip, $ip]);
```
Error creating user in Install - Step 3
User created after add `'about'` after `'birthday'`.
----------------------------------------------------
При установке не создаётся пользователь на 3 шаге.
Пользователь создался после добавления `'about'` после `'birthday'`.

**Comment by qexyorg** [comment]
Это связано с выставленной строгостью запросов в MySQL.

Отключение данной строгости так же решает этот вопрос:
`GLOBAL SET sql_mode=''`
